

const list = [
    {
      id: 1,
      title: "flat shoes(black)",
      store: "by versace | 25 April 2022",
      price: 200,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqvneGloZovCkmTTr9K_HYblreCSwbHwS-fw&usqp=CAU",
      amount: 1,
    },
    {
      id: 2,
      title: "sneaker for women",
      store: "by fend  | 1 September 2020",
      price: 98,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJVqy-2iw5GyehwrlKnnaeCmI17gHBmQ1feg&usqp=CAU",
      amount: 1,
    },
    {
      id: 3,
      title: "women hells(red)",
      store: "by fenty  | 25 November 2018",
      price: 143,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBwCWLDoKNN9Ee0-3AcRxYDMT5x_hIYK62w&usqp=CAU",
      amount: 1,
    },
    {
      id: 4,
      title: "low sneaker(white)",
      store: "by lous vouitton | 8 April 2021",
      price: 57,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOtqZ873CTrwOQJYAMkWEq3pdc_rGx3hJFwpPcYyUS4TePDYQkOaV-Ft0iTRJQW3aBeMY&usqp=CAU",
      amount: 1,
    },
    {
      id: 5,
      title: "latest versace sneaker(green)",
      store: "  by versace| 1 January 2019",
      price: 149,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1SuoQud_7EsVMfeoBFvsk14eJc3Bhx9RoA&usqp=CAU",
      amount: 1,
    },
    {
      id: 6,
      title: "boots(black)",
      store: "by puma| 30 September 2020",
      price: 135,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXxYVQZkU9Xfis22gBjdPC-bZ5D1czV5VD2g&usqp=CAU",
      amount: 1,
    },
    {
      id: 7,
      title: "jordan(2)",
      store: " by adidas| 1 January 2021",
      price: 693,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqBhEjAAzHL0-YeEOMCje1YRCA5ReXTXwLYQ&usqp=CAU",
      amount: 1,
    },
    {
      id: 8,
      title: "elegant hells(black)",
      store: " by yeezy| 2 December 2016",
      price: 500,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlgk7Vl6zSJ_W7bTmlGh9ZM7uSZ9bOXxTVKA&usqp=CAU",
      amount: 1,
    },
    {
      id: 9,
      title: " elegant hells(black)",
      store: "by yeezy| 2 December 2016",
      price: 80,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlgk7Vl6zSJ_W7bTmlGh9ZM7uSZ9bOXxTVKA&usqp=CAU",
      amount: 1,
    },
    {
      id: 10,
      title: "hells(pink)",
      store: "by nike| 1 September 2021",
      price: 86,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnpy7O2WEsjlSALzdaNdFKQyUqdq8IxEmrfQ&usqp=CAU",
      amount: 1,
    },
    {
      id: 11,
      title: "hells(yellow)",
      store: "by  essentials | 13 february 2021",
      price: 120,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOgPs4rIxSv1gVL41JELxo6uO-c0WZaxp8ig&usqp=CAU",
      amount: 1,
    },
    {
      id: 12,
      title: "sneaker(white)",
      store: "by fashinova | 1 January 2023",
      price: 157,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIC_wzytYteyLMwpA9btgHvbxUM7Lx8B_Gh_abB12D7uvv5HqqYUOahNqF-AWa-eltMKM&usqp=CAU",
      amount: 1,
    },
];

export default list;